"""Add tips in city model

Revision ID: 031e21406293
Revises: a702fd1aca9a
Create Date: 2025-05-07 12:10:42.480802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031e21406293'
down_revision = 'a702fd1aca9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_spots', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tips', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('tips')
        batch_op.drop_column('main_spots')

    # ### end Alembic commands ###
