"""Add weatherdata to Share

Revision ID: 5ef8211c7625
Revises: 031e21406293
Create Date: 2025-05-07 21:28:39.154002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef8211c7625'
down_revision = '031e21406293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('WeatherData', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_column('WeatherData')

    # ### end Alembic commands ###
