"""Add read, delete, favorite column to Share model

Revision ID: 870cbf9a816f
Revises: 5ef8211c7625
Create Date: 2025-05-08 15:43:57.733161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870cbf9a816f'
down_revision = '5ef8211c7625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weatherdata', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.drop_column('weatherData')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weatherData', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_read')
        batch_op.drop_column('weatherdata')

    # ### end Alembic commands ###
