"""Add Share model

Revision ID: 91cc2d323bde
Revises: a87f95bd85d3
Create Date: 2025-05-06 11:09:00.483449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cc2d323bde'
down_revision = 'a87f95bd85d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('shared_by', sa.Integer(), nullable=False),
    sa.Column('shared_to', sa.Integer(), nullable=False),
    sa.Column('share_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shared_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share')
    # ### end Alembic commands ###
